# Generated by Django 5.1.6 on 2025-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_item_price_alter_item_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
